version: '3.9'
services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - postgre-acgastropub:/var/lib/postgresql/data
    env_file: ../envs/.prod.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    build: ./
    ports: 
      - 8000:8000
    volumes: 
      - ../:/app
    env_file: ../envs/.prod.env
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgre-acgastropub:
    external: true
